const LANGUAGE_OPTIONS = [
    { locale: 'ko-KR', nativeName: '한국어', englishName: 'Korean' },
    { locale: 'en-US', nativeName: 'English (United States)', englishName: 'English' },
    { locale: 'en-GB', nativeName: 'English (United Kingdom)', englishName: 'English (UK)' },
    { locale: 'ja-JP', nativeName: '日本語', englishName: 'Japanese' },
    { locale: 'zh-CN', nativeName: '简体中文', englishName: 'Chinese (Simplified)' },
    { locale: 'zh-TW', nativeName: '繁體中文', englishName: 'Chinese (Traditional)' },
    { locale: 'fr-FR', nativeName: 'Français', englishName: 'French' },
    { locale: 'de-DE', nativeName: 'Deutsch', englishName: 'German' },
    { locale: 'es-MX', nativeName: 'Español (México)', englishName: 'Spanish (Mexico)' },
    { locale: 'es-ES', nativeName: 'Español (España)', englishName: 'Spanish (Spain)' },
    { locale: 'pt-BR', nativeName: 'Português (Brasil)', englishName: 'Portuguese (Brazil)' },
    { locale: 'pt-PT', nativeName: 'Português (Portugal)', englishName: 'Portuguese (Portugal)' },
    { locale: 'ru-RU', nativeName: 'Русский', englishName: 'Russian' },
    { locale: 'ar-SA', nativeName: 'العربية', englishName: 'Arabic' },
    { locale: 'hi-IN', nativeName: 'हिन्दी', englishName: 'Hindi' },
    { locale: 'vi-VN', nativeName: 'Tiếng Việt', englishName: 'Vietnamese' }
];

const SOURCE_TO_KEY = {
    '헤더 파일이 컴파일 중 여러 번 중복 포함(include)되는 것을 방지합니다.': 'headerOnce',
    '헤더 중복 포함 방지(인클루드 가드): 해당 매크로가 정의되지 않았을 때만 아래 코드를 포함합니다.': 'guardIfndef',
    '헤더 중복 포함 방지 플래그를 정의하여 중복 컴파일을 차단합니다.': 'guardDefine',
    '조건부 컴파일 전처리기(#ifndef / #ifdef / #if)의 끝을 나타냅니다.': 'conditionalEnd',
    'printf와 scanf 등 표준 입출력 함수를 사용하기 위해 표준 입출력 헤더를 포함합니다.': 'includeStdio',
    '동적 메모리 할당(malloc) 및 유틸리티 함수를 사용하기 위해 헤더를 포함합니다.': 'includeStdlib',
    '문자열 복사, 비교 등 문자열 조작 함수를 사용하기 위해 헤더를 포함합니다.': 'includeString',
    '제곱근, 거듭제곱 등 수학 연산 함수를 사용하기 위해 헤더를 포함합니다.': 'includeMath',
    'C 언어에서 bool(true, false) 타입을 사용하기 위해 헤더를 포함합니다.': 'includeBool',
    '시간 측정 및 날짜/시간 처리를 위해 시간 헤더를 포함합니다.': 'includeTime',
    '프로그램에 필요한 C 표준 라이브러리 헤더 파일을 포함합니다.': 'includeStandard',
    '프로젝트 내부에서 작성한 사용자 정의 헤더 파일을 포함합니다.': 'includeUser',
    '상수나 매크로를 정의하여 가독성을 높이고 일괄 변경을 용이하게 합니다.': 'macro',
    '연관된 여러 데이터를 하나로 묶는 구조체를 정의하고 새 타입명을 부여합니다.': 'typedefStruct',
    '구조체 정의를 마치고 새로운 자료형 타입명으로 등록합니다.': 'structEnd',
    '사용자 정의 데이터 타입인 구조체를 선언합니다.': 'structDecl',
    '기존 자료형에 직관적인 새 이름을 부여하는 타입 재정의(typedef)입니다.': 'typedef',
    '다른 소스 파일에 정의된 전역 변수 또는 함수를 현재 파일에서 참조할 수 있게 선언합니다.': 'externRef',
    '키보드(표준 입력)로부터 서식에 맞추어 데이터를 입력받아 변수에 저장합니다.': 'formattedInput',
    '서식 문자열에 맞추어 화면에 텍스트와 변수 값을 출력합니다.': 'formattedOutput',
    '프로그램 실행이 시작되는 메인(main) 함수입니다.': 'main',
    '다른 파일이나 함수에서 호출할 수 있도록 함수의 반환형과 매개변수를 미리 선언하는 함수 원형(프로토타입)입니다.': 'prototype',
    '특정 기능을 수행하는 함수의 본문을 정의합니다.': 'function',
    '특정 작업을 수행하는 사용자 정의 함수를 정의합니다.': 'function',
    '작업을 수행할 함수를 정의합니다.': 'function',
    '문자열을 저장하기 위한 문자형(char) 배열을 선언합니다.': 'charArray',
    '데이터를 저장하고 처리하기 위한 변수를 선언합니다.': 'variable',
    '값을 저장할 변수를 선언합니다.': 'variable',
    '주어진 조건식이 참(True)인지 판별하여 조건에 맞을 때 실행합니다.': 'if',
    '조건을 검사하여 참일 때 하위 코드를 실행합니다.': 'if',
    '조건식을 평가하여 분기 실행합니다.': 'if',
    '앞선 조건이 거짓일 때 새로운 조건식을 검사하여 분기합니다.': 'elseIf',
    '앞선 조건이 아닐 때 새로운 조건을 검사합니다.': 'elseIf',
    '위의 모든 조건이 만족되지 않을 때 기본으로 실행되는 블록입니다.': 'else',
    '위 조건들이 모두 거짓일 때 실행할 기본 블록입니다.': 'else',
    '초기식, 조건식, 증감식에 따라 정해진 횟수만큼 반복 실행합니다.': 'for',
    '시퀀스(리스트, 범위 등)의 항목을 하나씩 순회하며 반복합니다.': 'for',
    '조건식이 참인 동안 내부 코드 블록을 계속 반복 실행합니다.': 'while',
    '조건이 참인 동안 반복을 계속 수행합니다.': 'while',
    '프로그램이 성공적으로 완료되었음을 운영체제에 알리고 0을 반환합니다.': 'returnSuccess',
    '함수의 실행을 즉시 종료하고 호출한 곳으로 돌아갑니다.': 'returnVoid',
    '함수의 실행을 마치고 결과값을 호출한 곳으로 반환합니다.': 'returnValue',
    '함수 실행을 종료하고 결과값을 반환합니다.': 'returnValue',
    '함수의 결과값을 반환하고 종료합니다.': 'returnValue',
    '필요한 외부 라이브러리나 모듈을 불러옵니다.': 'importModule',
    '사용자로부터 키보드 입력을 받아 문자열로 저장합니다.': 'input',
    '화면에 문자열이나 계산 결과를 출력합니다.': 'print',
    '브라우저 콘솔이나 터미널에 메시지를 출력합니다.': 'consoleLog'
};

const CATALOGS = {
    'ko-KR': {
        headerOnce: '헤더 파일이 컴파일 중 여러 번 중복 포함(include)되는 것을 방지합니다.',
        guardIfndef: '헤더 중복 포함 방지(인클루드 가드): 해당 매크로가 정의되지 않았을 때만 아래 코드를 포함합니다.',
        guardDefine: '헤더 중복 포함 방지 플래그를 정의하여 중복 컴파일을 차단합니다.',
        conditionalEnd: '조건부 컴파일 전처리기의 끝을 나타냅니다.',
        includeStdio: 'printf와 scanf 등 표준 입출력 함수를 사용하기 위해 표준 입출력 헤더를 포함합니다.',
        includeStdlib: '동적 메모리 할당과 유틸리티 함수를 사용하기 위해 표준 라이브러리 헤더를 포함합니다.',
        includeString: '문자열 복사와 비교 등 문자열 조작 함수를 사용하기 위해 헤더를 포함합니다.',
        includeMath: '제곱근과 거듭제곱 등 수학 연산 함수를 사용하기 위해 헤더를 포함합니다.',
        includeBool: 'C 언어에서 bool 타입을 사용하기 위해 헤더를 포함합니다.',
        includeTime: '시간 측정과 날짜 및 시간 처리를 위해 헤더를 포함합니다.',
        includeStandard: '프로그램에 필요한 C 표준 라이브러리 헤더 파일을 포함합니다.',
        includeUser: '프로젝트 내부에서 작성한 사용자 정의 헤더 파일을 포함합니다.',
        macro: '상수나 매크로를 정의하여 가독성을 높이고 일괄 변경을 쉽게 합니다.',
        typedefStruct: '연관된 여러 데이터를 하나로 묶는 구조체를 정의하고 새 타입명을 부여합니다.',
        structEnd: '구조체 정의를 마치고 새로운 자료형 타입명으로 등록합니다.',
        structDecl: '사용자 정의 데이터 타입인 구조체를 선언합니다.',
        typedef: '기존 자료형에 직관적인 새 이름을 부여하는 타입 재정의입니다.',
        externRef: '다른 소스 파일에 정의된 전역 변수 또는 함수를 현재 파일에서 참조할 수 있게 선언합니다.',
        formattedInput: '표준 입력으로부터 서식에 맞춰 데이터를 입력받아 변수에 저장합니다.',
        formattedOutput: '서식 문자열에 맞춰 화면에 텍스트와 변수 값을 출력합니다.',
        main: '프로그램 실행이 시작되는 main 함수입니다.',
        prototype: '다른 곳에서 호출할 수 있도록 함수의 반환형과 매개변수를 미리 선언합니다.',
        function: '특정 작업을 수행하는 함수를 정의합니다.',
        charArray: '문자열을 저장하기 위한 문자형 배열을 선언합니다.',
        variable: '데이터를 저장하고 처리하기 위한 변수를 선언합니다.',
        if: '조건을 검사하여 참일 때 해당 코드를 실행합니다.',
        elseIf: '앞선 조건이 거짓일 때 새로운 조건을 검사합니다.',
        else: '앞선 조건들이 모두 거짓일 때 실행되는 기본 블록입니다.',
        for: '정해진 조건이나 항목에 따라 반복 실행합니다.',
        while: '조건이 참인 동안 반복 실행합니다.',
        returnSuccess: '프로그램이 성공적으로 끝났음을 알리고 0을 반환합니다.',
        returnVoid: '함수 실행을 즉시 끝내고 호출한 곳으로 돌아갑니다.',
        returnValue: '함수 실행을 끝내고 결과값을 반환합니다.',
        importModule: '필요한 외부 라이브러리나 모듈을 불러옵니다.',
        input: '사용자로부터 키보드 입력을 받아 저장합니다.',
        print: '화면에 문자열이나 계산 결과를 출력합니다.',
        consoleLog: '브라우저 콘솔이나 터미널에 메시지를 출력합니다.'
    },
    'en-US': {
        headerOnce: 'Prevents this header from being included more than once during compilation.',
        guardIfndef: 'Starts an include guard so the following code is included only when this macro is not defined.',
        guardDefine: 'Defines the include-guard flag to prevent duplicate inclusion.',
        conditionalEnd: 'Marks the end of a conditional preprocessor block.',
        includeStdio: 'Includes the standard I/O header for functions such as printf and scanf.',
        includeStdlib: 'Includes the standard library header for memory allocation and utility functions.',
        includeString: 'Includes string utilities for operations such as copying and comparing text.',
        includeMath: 'Includes math functions such as square root and power operations.',
        includeBool: 'Includes Boolean support so C can use the bool type.',
        includeTime: 'Includes time utilities for measuring time and handling dates or times.',
        includeStandard: 'Includes a C standard-library header required by the program.',
        includeUser: 'Includes a project-specific user-defined header file.',
        macro: 'Defines a constant or macro to improve readability and make changes easier.',
        typedefStruct: 'Defines a structure that groups related data and assigns it a new type name.',
        structEnd: 'Finishes the structure definition and registers its type name.',
        structDecl: 'Declares a structure as a user-defined data type.',
        typedef: 'Creates a clearer alias for an existing data type with typedef.',
        externRef: 'Declares a global variable or function that is defined in another source file.',
        formattedInput: 'Reads formatted data from standard input and stores it in variables.',
        formattedOutput: 'Prints text and variable values using a format string.',
        main: 'Defines the main function where program execution begins.',
        prototype: 'Declares a function return type and parameters before the function is called elsewhere.',
        function: 'Defines a function that performs a specific task.',
        charArray: 'Declares a character array used to store a string.',
        variable: 'Declares a variable used to store and process data.',
        if: 'Checks a condition and runs this code when the condition is true.',
        elseIf: 'Checks another condition when the previous condition was false.',
        else: 'Runs this default block when the previous conditions were false.',
        for: 'Repeats code according to a sequence, range, or loop condition.',
        while: 'Repeats the code while the condition remains true.',
        returnSuccess: 'Returns 0 to indicate that the program completed successfully.',
        returnVoid: 'Ends the function immediately and returns to the caller.',
        returnValue: 'Ends the function and returns a result to the caller.',
        importModule: 'Imports a library or module required by the program.',
        input: 'Reads keyboard input from the user and stores it.',
        print: 'Prints text or calculation results to the screen.',
        consoleLog: 'Prints a message to the browser console or terminal.'
    },
    'ja-JP': {
        headerOnce: 'コンパイル時にこのヘッダーファイルが重複して読み込まれるのを防ぎます。',
        guardIfndef: 'このマクロが未定義の場合だけ後続コードを含めるインクルードガードを開始します。',
        guardDefine: '重複読み込みを防ぐためのインクルードガード用フラグを定義します。',
        conditionalEnd: '条件付きプリプロセッサブロックの終了を示します。',
        includeStdio: 'printf や scanf などを使うために標準入出力ヘッダーを読み込みます。',
        includeStdlib: 'メモリ確保や各種ユーティリティ関数を使うために標準ライブラリヘッダーを読み込みます。',
        includeString: '文字列のコピーや比較などを行うために文字列操作ヘッダーを読み込みます。',
        includeMath: '平方根やべき乗などの数学関数を使うために数学ヘッダーを読み込みます。',
        includeBool: 'C で bool 型を使うための真偽値サポートを読み込みます。',
        includeTime: '時間計測や日時処理のためのヘッダーを読み込みます。',
        includeStandard: 'プログラムに必要な C 標準ライブラリのヘッダーを読み込みます。',
        includeUser: 'プロジェクト内で作成したユーザー定義ヘッダーを読み込みます。',
        macro: '可読性を高め変更を容易にするため、定数またはマクロを定義します。',
        typedefStruct: '関連データをまとめる構造体を定義し、新しい型名を付けます。',
        structEnd: '構造体の定義を終了し、新しい型名として登録します。',
        structDecl: 'ユーザー定義データ型として構造体を宣言します。',
        typedef: 'typedef を使って既存のデータ型に分かりやすい別名を付けます。',
        externRef: '別のソースファイルで定義されたグローバル変数または関数を参照できるよう宣言します。',
        formattedInput: '標準入力から書式に従ってデータを読み取り、変数に保存します。',
        formattedOutput: '書式文字列に従ってテキストや変数の値を出力します。',
        main: 'プログラムの実行が始まる main 関数を定義します。',
        prototype: '別の場所から呼び出せるよう、関数の戻り値型と引数を先に宣言します。',
        function: '特定の処理を行う関数を定義します。',
        charArray: '文字列を保存するための文字配列を宣言します。',
        variable: 'データを保存して処理するための変数を宣言します。',
        if: '条件を確認し、真の場合にこのコードを実行します。',
        elseIf: '前の条件が偽だった場合に別の条件を確認します。',
        else: '前の条件がすべて偽だった場合にこの既定ブロックを実行します。',
        for: 'シーケンスや範囲、条件に従ってコードを繰り返します。',
        while: '条件が真である間、コードを繰り返します。',
        returnSuccess: 'プログラムが正常終了したことを示すため 0 を返します。',
        returnVoid: '関数を直ちに終了して呼び出し元へ戻ります。',
        returnValue: '関数を終了し、結果を呼び出し元へ返します。',
        importModule: '必要なライブラリまたはモジュールを読み込みます。',
        input: 'ユーザーからキーボード入力を受け取り保存します。',
        print: '文字列や計算結果を画面に出力します。',
        consoleLog: 'ブラウザーコンソールまたはターミナルにメッセージを出力します。'
    },
    'zh-CN': {
        headerOnce: '防止该头文件在编译过程中被重复包含。',
        guardIfndef: '开始包含保护，仅当该宏尚未定义时才包含后续代码。',
        guardDefine: '定义包含保护标志以防止重复包含。',
        conditionalEnd: '表示条件预处理代码块的结束。',
        includeStdio: '包含标准输入输出头文件，以使用 printf、scanf 等函数。',
        includeStdlib: '包含标准库头文件，以使用内存分配和实用函数。',
        includeString: '包含字符串处理头文件，以进行复制、比较等操作。',
        includeMath: '包含数学头文件，以使用平方根、幂等数学函数。',
        includeBool: '包含布尔类型支持，使 C 可以使用 bool。',
        includeTime: '包含时间处理头文件，用于计时以及日期和时间处理。',
        includeStandard: '包含程序所需的 C 标准库头文件。',
        includeUser: '包含项目内部编写的自定义头文件。',
        macro: '定义常量或宏，以提高可读性并便于统一修改。',
        typedefStruct: '定义用于组织相关数据的结构体，并赋予新的类型名。',
        structEnd: '结束结构体定义并注册新的类型名。',
        structDecl: '声明一个用户自定义的结构体数据类型。',
        typedef: '使用 typedef 为现有数据类型创建更直观的别名。',
        externRef: '声明在其他源文件中定义的全局变量或函数。',
        formattedInput: '按照格式从标准输入读取数据并保存到变量中。',
        formattedOutput: '按照格式字符串输出文本和变量值。',
        main: '定义程序开始执行的 main 函数。',
        prototype: '预先声明函数的返回类型和参数，以便在其他位置调用。',
        function: '定义一个执行特定任务的函数。',
        charArray: '声明用于保存字符串的字符数组。',
        variable: '声明用于保存和处理数据的变量。',
        if: '检查条件，并在条件为真时执行此代码。',
        elseIf: '当前一个条件为假时检查另一个条件。',
        else: '当前面的条件都为假时执行此默认代码块。',
        for: '根据序列、范围或循环条件重复执行代码。',
        while: '在条件为真时持续重复执行代码。',
        returnSuccess: '返回 0，表示程序已成功结束。',
        returnVoid: '立即结束函数并返回调用处。',
        returnValue: '结束函数并向调用处返回结果。',
        importModule: '导入程序所需的库或模块。',
        input: '读取用户的键盘输入并保存。',
        print: '将文本或计算结果输出到屏幕。',
        consoleLog: '向浏览器控制台或终端输出消息。'
    },
    'zh-TW': {
        headerOnce: '防止此標頭檔在編譯時被重複包含。',
        guardIfndef: '開始包含防護，只有在此巨集尚未定義時才包含後續程式碼。',
        guardDefine: '定義包含防護旗標以避免重複包含。',
        conditionalEnd: '表示條件式前置處理區塊的結束。',
        includeStdio: '包含標準輸入輸出標頭，以使用 printf、scanf 等函式。',
        includeStdlib: '包含標準函式庫標頭，以使用記憶體配置與工具函式。',
        includeString: '包含字串處理標頭，以進行複製、比較等操作。',
        includeMath: '包含數學標頭，以使用平方根、次方等數學函式。',
        includeBool: '包含布林型別支援，讓 C 可以使用 bool。',
        includeTime: '包含時間處理標頭，用於計時以及日期與時間處理。',
        includeStandard: '包含程式所需的 C 標準函式庫標頭。',
        includeUser: '包含專案內自行撰寫的自訂標頭檔。',
        macro: '定義常數或巨集，以提高可讀性並方便統一修改。',
        typedefStruct: '定義用來整合相關資料的結構，並指定新的型別名稱。',
        structEnd: '結束結構定義並註冊新的型別名稱。',
        structDecl: '宣告使用者自訂的結構資料型別。',
        typedef: '使用 typedef 為既有資料型別建立較直觀的別名。',
        externRef: '宣告定義於其他原始碼檔案中的全域變數或函式。',
        formattedInput: '依照格式從標準輸入讀取資料並儲存到變數中。',
        formattedOutput: '依照格式字串輸出文字與變數值。',
        main: '定義程式開始執行的 main 函式。',
        prototype: '預先宣告函式的回傳型別與參數，以便在其他位置呼叫。',
        function: '定義執行特定工作的函式。',
        charArray: '宣告用來儲存字串的字元陣列。',
        variable: '宣告用來儲存與處理資料的變數。',
        if: '檢查條件，並在條件為真時執行此程式碼。',
        elseIf: '前一個條件為假時檢查另一個條件。',
        else: '前面的條件都為假時執行此預設區塊。',
        for: '依照序列、範圍或迴圈條件重複執行程式碼。',
        while: '條件為真時持續重複執行程式碼。',
        returnSuccess: '回傳 0，表示程式已成功結束。',
        returnVoid: '立即結束函式並回到呼叫端。',
        returnValue: '結束函式並將結果回傳給呼叫端。',
        importModule: '匯入程式所需的函式庫或模組。',
        input: '讀取使用者的鍵盤輸入並儲存。',
        print: '將文字或計算結果輸出到畫面。',
        consoleLog: '將訊息輸出到瀏覽器主控台或終端機。'
    },
    'fr-FR': {
        headerOnce: 'Empêche ce fichier d’en-tête d’être inclus plusieurs fois pendant la compilation.',
        guardIfndef: 'Démarre une garde d’inclusion afin que le code suivant ne soit inclus que si cette macro n’est pas définie.',
        guardDefine: 'Définit l’indicateur de garde d’inclusion pour éviter les inclusions multiples.',
        conditionalEnd: 'Marque la fin d’un bloc conditionnel du préprocesseur.',
        includeStdio: 'Inclut l’en-tête d’entrée/sortie standard pour utiliser printf, scanf, etc.',
        includeStdlib: 'Inclut la bibliothèque standard pour l’allocation mémoire et les fonctions utilitaires.',
        includeString: 'Inclut les fonctions de manipulation de chaînes, comme la copie et la comparaison.',
        includeMath: 'Inclut les fonctions mathématiques comme la racine carrée et les puissances.',
        includeBool: 'Inclut la prise en charge du type booléen bool en C.',
        includeTime: 'Inclut les outils de mesure du temps et de gestion des dates et heures.',
        includeStandard: 'Inclut un en-tête de la bibliothèque standard C nécessaire au programme.',
        includeUser: 'Inclut un fichier d’en-tête personnalisé du projet.',
        macro: 'Définit une constante ou une macro pour améliorer la lisibilité et faciliter les modifications.',
        typedefStruct: 'Définit une structure regroupant des données liées et lui attribue un nouveau nom de type.',
        structEnd: 'Termine la définition de la structure et enregistre son nom de type.',
        structDecl: 'Déclare une structure comme type de données défini par l’utilisateur.',
        typedef: 'Crée avec typedef un alias plus clair pour un type de données existant.',
        externRef: 'Déclare une variable globale ou une fonction définie dans un autre fichier source.',
        formattedInput: 'Lit des données formatées depuis l’entrée standard et les stocke dans des variables.',
        formattedOutput: 'Affiche du texte et des valeurs de variables à l’aide d’une chaîne de format.',
        main: 'Définit la fonction main où commence l’exécution du programme.',
        prototype: 'Déclare à l’avance le type de retour et les paramètres d’une fonction.',
        function: 'Définit une fonction qui effectue une tâche précise.',
        charArray: 'Déclare un tableau de caractères utilisé pour stocker une chaîne.',
        variable: 'Déclare une variable utilisée pour stocker et traiter des données.',
        if: 'Teste une condition et exécute ce code si elle est vraie.',
        elseIf: 'Teste une autre condition lorsque la précédente est fausse.',
        else: 'Exécute ce bloc par défaut lorsque les conditions précédentes sont fausses.',
        for: 'Répète le code selon une séquence, une plage ou une condition de boucle.',
        while: 'Répète le code tant que la condition reste vraie.',
        returnSuccess: 'Renvoie 0 pour indiquer que le programme s’est terminé correctement.',
        returnVoid: 'Termine immédiatement la fonction et revient à l’appelant.',
        returnValue: 'Termine la fonction et renvoie un résultat à l’appelant.',
        importModule: 'Importe une bibliothèque ou un module nécessaire au programme.',
        input: 'Lit une saisie clavier de l’utilisateur et la stocke.',
        print: 'Affiche du texte ou le résultat d’un calcul à l’écran.',
        consoleLog: 'Affiche un message dans la console du navigateur ou le terminal.'
    },
    'de-DE': {
        headerOnce: 'Verhindert, dass diese Headerdatei beim Kompilieren mehrfach eingebunden wird.',
        guardIfndef: 'Startet einen Include-Guard, sodass der folgende Code nur eingebunden wird, wenn dieses Makro nicht definiert ist.',
        guardDefine: 'Definiert das Include-Guard-Flag, um mehrfaches Einbinden zu verhindern.',
        conditionalEnd: 'Markiert das Ende eines bedingten Präprozessorblocks.',
        includeStdio: 'Bindet den Standard-E/A-Header für Funktionen wie printf und scanf ein.',
        includeStdlib: 'Bindet die Standardbibliothek für Speicherverwaltung und Hilfsfunktionen ein.',
        includeString: 'Bindet Funktionen zur Zeichenkettenverarbeitung wie Kopieren und Vergleichen ein.',
        includeMath: 'Bindet mathematische Funktionen wie Quadratwurzel und Potenz ein.',
        includeBool: 'Bindet die Unterstützung für den bool-Typ in C ein.',
        includeTime: 'Bindet Funktionen zur Zeitmessung sowie Datums- und Zeitverarbeitung ein.',
        includeStandard: 'Bindet einen vom Programm benötigten Header der C-Standardbibliothek ein.',
        includeUser: 'Bindet eine projektspezifische benutzerdefinierte Headerdatei ein.',
        macro: 'Definiert eine Konstante oder ein Makro für bessere Lesbarkeit und einfachere Änderungen.',
        typedefStruct: 'Definiert eine Struktur für zusammengehörige Daten und vergibt einen neuen Typnamen.',
        structEnd: 'Beendet die Strukturdefinition und registriert den neuen Typnamen.',
        structDecl: 'Deklariert eine Struktur als benutzerdefinierten Datentyp.',
        typedef: 'Erstellt mit typedef einen verständlicheren Alias für einen vorhandenen Datentyp.',
        externRef: 'Deklariert eine globale Variable oder Funktion, die in einer anderen Quelldatei definiert ist.',
        formattedInput: 'Liest formatierte Daten von der Standardeingabe und speichert sie in Variablen.',
        formattedOutput: 'Gibt Text und Variablenwerte mithilfe einer Formatzeichenfolge aus.',
        main: 'Definiert die main-Funktion, an der die Programmausführung beginnt.',
        prototype: 'Deklariert Rückgabetyp und Parameter einer Funktion, bevor sie an anderer Stelle aufgerufen wird.',
        function: 'Definiert eine Funktion, die eine bestimmte Aufgabe ausführt.',
        charArray: 'Deklariert ein Zeichenarray zum Speichern einer Zeichenkette.',
        variable: 'Deklariert eine Variable zum Speichern und Verarbeiten von Daten.',
        if: 'Prüft eine Bedingung und führt diesen Code aus, wenn sie wahr ist.',
        elseIf: 'Prüft eine weitere Bedingung, wenn die vorherige Bedingung falsch war.',
        else: 'Führt diesen Standardblock aus, wenn die vorherigen Bedingungen falsch waren.',
        for: 'Wiederholt Code anhand einer Sequenz, eines Bereichs oder einer Schleifenbedingung.',
        while: 'Wiederholt den Code, solange die Bedingung wahr bleibt.',
        returnSuccess: 'Gibt 0 zurück, um einen erfolgreichen Programmabschluss anzuzeigen.',
        returnVoid: 'Beendet die Funktion sofort und kehrt zum Aufrufer zurück.',
        returnValue: 'Beendet die Funktion und gibt ein Ergebnis an den Aufrufer zurück.',
        importModule: 'Importiert eine vom Programm benötigte Bibliothek oder ein Modul.',
        input: 'Liest eine Tastatureingabe des Benutzers und speichert sie.',
        print: 'Gibt Text oder Berechnungsergebnisse auf dem Bildschirm aus.',
        consoleLog: 'Gibt eine Nachricht in der Browserkonsole oder im Terminal aus.'
    },
    'es-MX': {
        headerOnce: 'Evita que este archivo de encabezado se incluya más de una vez durante la compilación.',
        guardIfndef: 'Inicia una guarda de inclusión para incluir el código siguiente solo si esta macro no está definida.',
        guardDefine: 'Define la bandera de la guarda de inclusión para evitar inclusiones duplicadas.',
        conditionalEnd: 'Marca el final de un bloque condicional del preprocesador.',
        includeStdio: 'Incluye el encabezado de entrada y salida estándar para usar funciones como printf y scanf.',
        includeStdlib: 'Incluye la biblioteca estándar para asignación de memoria y funciones de utilidad.',
        includeString: 'Incluye funciones para manipular cadenas, como copiar y comparar texto.',
        includeMath: 'Incluye funciones matemáticas como raíz cuadrada y potencias.',
        includeBool: 'Incluye compatibilidad con el tipo booleano bool en C.',
        includeTime: 'Incluye herramientas para medir el tiempo y manejar fechas y horas.',
        includeStandard: 'Incluye un encabezado de la biblioteca estándar de C que necesita el programa.',
        includeUser: 'Incluye un archivo de encabezado personalizado del proyecto.',
        macro: 'Define una constante o macro para mejorar la legibilidad y facilitar cambios.',
        typedefStruct: 'Define una estructura que agrupa datos relacionados y le asigna un nuevo nombre de tipo.',
        structEnd: 'Termina la definición de la estructura y registra su nombre de tipo.',
        structDecl: 'Declara una estructura como un tipo de datos definido por el usuario.',
        typedef: 'Crea con typedef un alias más claro para un tipo de datos existente.',
        externRef: 'Declara una variable global o función definida en otro archivo fuente.',
        formattedInput: 'Lee datos con formato desde la entrada estándar y los guarda en variables.',
        formattedOutput: 'Muestra texto y valores de variables usando una cadena de formato.',
        main: 'Define la función main donde comienza la ejecución del programa.',
        prototype: 'Declara con anticipación el tipo de retorno y los parámetros de una función.',
        function: 'Define una función que realiza una tarea específica.',
        charArray: 'Declara un arreglo de caracteres para almacenar una cadena.',
        variable: 'Declara una variable para almacenar y procesar datos.',
        if: 'Evalúa una condición y ejecuta este código cuando es verdadera.',
        elseIf: 'Evalúa otra condición cuando la condición anterior fue falsa.',
        else: 'Ejecuta este bloque predeterminado cuando las condiciones anteriores fueron falsas.',
        for: 'Repite código según una secuencia, un rango o una condición de ciclo.',
        while: 'Repite el código mientras la condición siga siendo verdadera.',
        returnSuccess: 'Devuelve 0 para indicar que el programa terminó correctamente.',
        returnVoid: 'Termina la función de inmediato y vuelve al punto que la llamó.',
        returnValue: 'Termina la función y devuelve un resultado al punto que la llamó.',
        importModule: 'Importa una biblioteca o módulo que necesita el programa.',
        input: 'Lee una entrada del teclado del usuario y la guarda.',
        print: 'Muestra texto o resultados de cálculos en la pantalla.',
        consoleLog: 'Muestra un mensaje en la consola del navegador o en la terminal.'
    },
    'pt-BR': {
        headerOnce: 'Impede que este arquivo de cabeçalho seja incluído mais de uma vez durante a compilação.',
        guardIfndef: 'Inicia uma proteção de inclusão para usar o código seguinte apenas se esta macro não estiver definida.',
        guardDefine: 'Define a marca da proteção de inclusão para impedir inclusões duplicadas.',
        conditionalEnd: 'Marca o fim de um bloco condicional do pré-processador.',
        includeStdio: 'Inclui o cabeçalho de entrada e saída padrão para usar funções como printf e scanf.',
        includeStdlib: 'Inclui a biblioteca padrão para alocação de memória e funções utilitárias.',
        includeString: 'Inclui funções de manipulação de strings, como cópia e comparação.',
        includeMath: 'Inclui funções matemáticas como raiz quadrada e potência.',
        includeBool: 'Inclui suporte ao tipo booleano bool em C.',
        includeTime: 'Inclui recursos para medir tempo e tratar datas e horários.',
        includeStandard: 'Inclui um cabeçalho da biblioteca padrão C necessário ao programa.',
        includeUser: 'Inclui um arquivo de cabeçalho personalizado do projeto.',
        macro: 'Define uma constante ou macro para melhorar a legibilidade e facilitar alterações.',
        typedefStruct: 'Define uma estrutura que agrupa dados relacionados e atribui um novo nome de tipo.',
        structEnd: 'Finaliza a definição da estrutura e registra o novo nome de tipo.',
        structDecl: 'Declara uma estrutura como um tipo de dado definido pelo usuário.',
        typedef: 'Cria com typedef um alias mais claro para um tipo de dado existente.',
        externRef: 'Declara uma variável global ou função definida em outro arquivo-fonte.',
        formattedInput: 'Lê dados formatados da entrada padrão e os armazena em variáveis.',
        formattedOutput: 'Exibe texto e valores de variáveis usando uma string de formato.',
        main: 'Define a função main onde a execução do programa começa.',
        prototype: 'Declara antecipadamente o tipo de retorno e os parâmetros de uma função.',
        function: 'Define uma função que executa uma tarefa específica.',
        charArray: 'Declara um vetor de caracteres para armazenar uma string.',
        variable: 'Declara uma variável usada para armazenar e processar dados.',
        if: 'Verifica uma condição e executa este código quando ela é verdadeira.',
        elseIf: 'Verifica outra condição quando a condição anterior era falsa.',
        else: 'Executa este bloco padrão quando as condições anteriores eram falsas.',
        for: 'Repete o código de acordo com uma sequência, intervalo ou condição de laço.',
        while: 'Repete o código enquanto a condição permanecer verdadeira.',
        returnSuccess: 'Retorna 0 para indicar que o programa terminou com sucesso.',
        returnVoid: 'Encerra a função imediatamente e retorna ao chamador.',
        returnValue: 'Encerra a função e retorna um resultado ao chamador.',
        importModule: 'Importa uma biblioteca ou módulo necessário ao programa.',
        input: 'Lê uma entrada de teclado do usuário e a armazena.',
        print: 'Exibe texto ou resultados de cálculos na tela.',
        consoleLog: 'Exibe uma mensagem no console do navegador ou no terminal.'
    },
    'ru-RU': {
        headerOnce: 'Предотвращает повторное подключение этого заголовочного файла при компиляции.',
        guardIfndef: 'Начинает защиту от повторного включения и добавляет код только если макрос ещё не определён.',
        guardDefine: 'Определяет флаг защиты от повторного включения.',
        conditionalEnd: 'Обозначает конец условного блока препроцессора.',
        includeStdio: 'Подключает стандартный ввод и вывод для функций printf, scanf и других.',
        includeStdlib: 'Подключает стандартную библиотеку для выделения памяти и служебных функций.',
        includeString: 'Подключает функции работы со строками, например копирование и сравнение.',
        includeMath: 'Подключает математические функции, например квадратный корень и степень.',
        includeBool: 'Подключает поддержку логического типа bool в C.',
        includeTime: 'Подключает средства измерения времени и обработки даты и времени.',
        includeStandard: 'Подключает необходимый программе заголовок стандартной библиотеки C.',
        includeUser: 'Подключает пользовательский заголовочный файл проекта.',
        macro: 'Определяет константу или макрос для улучшения читаемости и упрощения изменений.',
        typedefStruct: 'Определяет структуру для связанных данных и назначает ей новое имя типа.',
        structEnd: 'Завершает определение структуры и регистрирует имя типа.',
        structDecl: 'Объявляет структуру как пользовательский тип данных.',
        typedef: 'Создаёт с помощью typedef более понятный псевдоним существующего типа.',
        externRef: 'Объявляет глобальную переменную или функцию, определённую в другом исходном файле.',
        formattedInput: 'Считывает форматированные данные из стандартного ввода и сохраняет их в переменные.',
        formattedOutput: 'Выводит текст и значения переменных по строке формата.',
        main: 'Определяет функцию main, с которой начинается выполнение программы.',
        prototype: 'Заранее объявляет тип возврата и параметры функции.',
        function: 'Определяет функцию, выполняющую конкретную задачу.',
        charArray: 'Объявляет массив символов для хранения строки.',
        variable: 'Объявляет переменную для хранения и обработки данных.',
        if: 'Проверяет условие и выполняет этот код, если оно истинно.',
        elseIf: 'Проверяет другое условие, если предыдущее было ложным.',
        else: 'Выполняет этот блок, если предыдущие условия были ложными.',
        for: 'Повторяет код по последовательности, диапазону или условию цикла.',
        while: 'Повторяет код, пока условие остаётся истинным.',
        returnSuccess: 'Возвращает 0, показывая успешное завершение программы.',
        returnVoid: 'Немедленно завершает функцию и возвращается к вызывающему коду.',
        returnValue: 'Завершает функцию и возвращает результат вызывающему коду.',
        importModule: 'Импортирует библиотеку или модуль, необходимый программе.',
        input: 'Считывает ввод пользователя с клавиатуры и сохраняет его.',
        print: 'Выводит текст или результаты вычислений на экран.',
        consoleLog: 'Выводит сообщение в консоль браузера или терминал.'
    },
    'ar-SA': {
        headerOnce: 'يمنع تضمين ملف الترويسة هذا أكثر من مرة أثناء الترجمة.',
        guardIfndef: 'يبدأ حارس تضمين بحيث يُضمَّن الكود التالي فقط إذا لم يكن هذا الماكرو معرّفًا.',
        guardDefine: 'يعرّف علامة حارس التضمين لمنع التضمين المتكرر.',
        conditionalEnd: 'يشير إلى نهاية كتلة شرطية للمعالج القبلي.',
        includeStdio: 'يضمّن ترويسة الإدخال والإخراج القياسية لاستخدام printf و scanf وغيرها.',
        includeStdlib: 'يضمّن المكتبة القياسية لتخصيص الذاكرة والدوال المساعدة.',
        includeString: 'يضمّن دوال معالجة السلاسل مثل النسخ والمقارنة.',
        includeMath: 'يضمّن الدوال الرياضية مثل الجذر التربيعي والأسس.',
        includeBool: 'يضمّن دعم النوع المنطقي bool في C.',
        includeTime: 'يضمّن أدوات قياس الوقت ومعالجة التاريخ والوقت.',
        includeStandard: 'يضمّن ترويسة من مكتبة C القياسية يحتاجها البرنامج.',
        includeUser: 'يضمّن ملف ترويسة مخصصًا من داخل المشروع.',
        macro: 'يعرّف ثابتًا أو ماكرو لتحسين الوضوح وتسهيل التعديلات.',
        typedefStruct: 'يعرّف بنية تجمع بيانات مترابطة ويمنحها اسم نوع جديدًا.',
        structEnd: 'ينهي تعريف البنية ويسجل اسم النوع الجديد.',
        structDecl: 'يعلن بنية كنوع بيانات يعرّفه المستخدم.',
        typedef: 'ينشئ باستخدام typedef اسمًا مستعارًا أوضح لنوع بيانات موجود.',
        externRef: 'يعلن متغيرًا عامًا أو دالة معرفة في ملف مصدر آخر.',
        formattedInput: 'يقرأ بيانات منسقة من الإدخال القياسي ويحفظها في متغيرات.',
        formattedOutput: 'يطبع النص وقيم المتغيرات باستخدام سلسلة تنسيق.',
        main: 'يعرّف الدالة main التي يبدأ منها تنفيذ البرنامج.',
        prototype: 'يعلن مسبقًا نوع الإرجاع ومعاملات الدالة.',
        function: 'يعرّف دالة تنفذ مهمة محددة.',
        charArray: 'يعلن مصفوفة محارف لتخزين سلسلة نصية.',
        variable: 'يعلن متغيرًا لتخزين البيانات ومعالجتها.',
        if: 'يفحص شرطًا وينفذ هذا الكود عندما يكون الشرط صحيحًا.',
        elseIf: 'يفحص شرطًا آخر عندما يكون الشرط السابق غير صحيح.',
        else: 'ينفذ هذه الكتلة الافتراضية عندما تكون الشروط السابقة غير صحيحة.',
        for: 'يكرر الكود وفق تسلسل أو نطاق أو شرط حلقة.',
        while: 'يكرر الكود ما دام الشرط صحيحًا.',
        returnSuccess: 'يعيد 0 للدلالة على انتهاء البرنامج بنجاح.',
        returnVoid: 'ينهي الدالة فورًا ويعود إلى المستدعي.',
        returnValue: 'ينهي الدالة ويعيد نتيجة إلى المستدعي.',
        importModule: 'يستورد مكتبة أو وحدة يحتاجها البرنامج.',
        input: 'يقرأ إدخال المستخدم من لوحة المفاتيح ويحفظه.',
        print: 'يعرض نصًا أو نتائج حسابية على الشاشة.',
        consoleLog: 'يعرض رسالة في وحدة تحكم المتصفح أو الطرفية.'
    },
    'hi-IN': {
        headerOnce: 'कम्पाइल के दौरान इस हेडर फ़ाइल को एक से अधिक बार शामिल होने से रोकता है।',
        guardIfndef: 'इन्क्लूड गार्ड शुरू करता है ताकि यह मैक्रो परिभाषित न होने पर ही आगे का कोड शामिल हो।',
        guardDefine: 'दोबारा शामिल होने से रोकने के लिए इन्क्लूड गार्ड फ़्लैग परिभाषित करता है।',
        conditionalEnd: 'सशर्त प्रीप्रोसेसर ब्लॉक का अंत दर्शाता है।',
        includeStdio: 'printf और scanf जैसे फ़ंक्शन के लिए मानक इनपुट/आउटपुट हेडर शामिल करता है।',
        includeStdlib: 'मेमोरी आवंटन और उपयोगिता फ़ंक्शन के लिए मानक लाइब्रेरी हेडर शामिल करता है।',
        includeString: 'कॉपी और तुलना जैसे स्ट्रिंग ऑपरेशन के लिए स्ट्रिंग हेडर शामिल करता है।',
        includeMath: 'वर्गमूल और घात जैसे गणितीय फ़ंक्शन के लिए मैथ हेडर शामिल करता है।',
        includeBool: 'C में bool प्रकार का उपयोग करने के लिए बूलियन समर्थन शामिल करता है।',
        includeTime: 'समय मापने और तारीख/समय संभालने के लिए टाइम हेडर शामिल करता है।',
        includeStandard: 'प्रोग्राम के लिए आवश्यक C मानक लाइब्रेरी हेडर शामिल करता है।',
        includeUser: 'प्रोजेक्ट में बनाई गई कस्टम हेडर फ़ाइल शामिल करता है।',
        macro: 'पठनीयता और आसान बदलाव के लिए स्थिरांक या मैक्रो परिभाषित करता है।',
        typedefStruct: 'संबंधित डेटा को समूहित करने वाली संरचना परिभाषित कर उसे नया प्रकार नाम देता है।',
        structEnd: 'संरचना की परिभाषा समाप्त कर नए प्रकार नाम को पंजीकृत करता है।',
        structDecl: 'उपयोगकर्ता-परिभाषित डेटा प्रकार के रूप में संरचना घोषित करता है।',
        typedef: 'typedef से मौजूदा डेटा प्रकार के लिए अधिक स्पष्ट उपनाम बनाता है।',
        externRef: 'किसी अन्य सोर्स फ़ाइल में परिभाषित वैश्विक चर या फ़ंक्शन घोषित करता है।',
        formattedInput: 'मानक इनपुट से स्वरूपित डेटा पढ़कर चर में संग्रहीत करता है।',
        formattedOutput: 'फ़ॉर्मेट स्ट्रिंग का उपयोग करके टेक्स्ट और चर के मान दिखाता है।',
        main: 'main फ़ंक्शन परिभाषित करता है जहाँ से प्रोग्राम का निष्पादन शुरू होता है।',
        prototype: 'फ़ंक्शन का रिटर्न प्रकार और पैरामीटर पहले से घोषित करता है।',
        function: 'किसी विशेष कार्य को करने वाला फ़ंक्शन परिभाषित करता है।',
        charArray: 'स्ट्रिंग संग्रहीत करने के लिए कैरेक्टर ऐरे घोषित करता है।',
        variable: 'डेटा संग्रहीत और संसाधित करने के लिए चर घोषित करता है।',
        if: 'शर्त जाँचता है और सही होने पर यह कोड चलाता है।',
        elseIf: 'पिछली शर्त गलत होने पर दूसरी शर्त जाँचता है।',
        else: 'पिछली सभी शर्तें गलत होने पर यह डिफ़ॉल्ट ब्लॉक चलाता है।',
        for: 'सीक्वेंस, रेंज या लूप शर्त के अनुसार कोड दोहराता है।',
        while: 'शर्त सही रहने तक कोड दोहराता है।',
        returnSuccess: 'प्रोग्राम के सफल समापन को दर्शाने के लिए 0 लौटाता है।',
        returnVoid: 'फ़ंक्शन को तुरंत समाप्त कर कॉल करने वाले स्थान पर लौटता है।',
        returnValue: 'फ़ंक्शन समाप्त कर परिणाम कॉल करने वाले स्थान पर लौटाता है।',
        importModule: 'प्रोग्राम के लिए आवश्यक लाइब्रेरी या मॉड्यूल आयात करता है।',
        input: 'उपयोगकर्ता से कीबोर्ड इनपुट पढ़कर संग्रहीत करता है।',
        print: 'स्क्रीन पर टेक्स्ट या गणना का परिणाम दिखाता है।',
        consoleLog: 'ब्राउज़र कंसोल या टर्मिनल में संदेश दिखाता है।'
    },
    'vi-VN': {
        headerOnce: 'Ngăn tệp header này được đưa vào nhiều lần trong quá trình biên dịch.',
        guardIfndef: 'Bắt đầu include guard để chỉ đưa mã phía sau vào khi macro này chưa được định nghĩa.',
        guardDefine: 'Định nghĩa cờ include guard để tránh đưa header vào nhiều lần.',
        conditionalEnd: 'Đánh dấu kết thúc một khối tiền xử lý có điều kiện.',
        includeStdio: 'Nạp header nhập/xuất chuẩn để dùng các hàm như printf và scanf.',
        includeStdlib: 'Nạp thư viện chuẩn cho cấp phát bộ nhớ và các hàm tiện ích.',
        includeString: 'Nạp các hàm xử lý chuỗi như sao chép và so sánh.',
        includeMath: 'Nạp các hàm toán học như căn bậc hai và lũy thừa.',
        includeBool: 'Nạp hỗ trợ kiểu Boolean bool trong C.',
        includeTime: 'Nạp công cụ đo thời gian và xử lý ngày giờ.',
        includeStandard: 'Nạp một header của thư viện chuẩn C mà chương trình cần.',
        includeUser: 'Nạp tệp header tùy chỉnh được viết trong dự án.',
        macro: 'Định nghĩa hằng hoặc macro để tăng khả năng đọc và giúp thay đổi dễ hơn.',
        typedefStruct: 'Định nghĩa cấu trúc gom các dữ liệu liên quan và đặt tên kiểu mới.',
        structEnd: 'Kết thúc định nghĩa cấu trúc và đăng ký tên kiểu mới.',
        structDecl: 'Khai báo cấu trúc như một kiểu dữ liệu do người dùng định nghĩa.',
        typedef: 'Dùng typedef để tạo bí danh rõ ràng hơn cho kiểu dữ liệu hiện có.',
        externRef: 'Khai báo biến toàn cục hoặc hàm được định nghĩa trong tệp nguồn khác.',
        formattedInput: 'Đọc dữ liệu có định dạng từ đầu vào chuẩn và lưu vào biến.',
        formattedOutput: 'In văn bản và giá trị biến bằng chuỗi định dạng.',
        main: 'Định nghĩa hàm main nơi chương trình bắt đầu thực thi.',
        prototype: 'Khai báo trước kiểu trả về và tham số của hàm.',
        function: 'Định nghĩa một hàm thực hiện nhiệm vụ cụ thể.',
        charArray: 'Khai báo mảng ký tự dùng để lưu chuỗi.',
        variable: 'Khai báo biến dùng để lưu và xử lý dữ liệu.',
        if: 'Kiểm tra điều kiện và chạy đoạn mã này khi điều kiện đúng.',
        elseIf: 'Kiểm tra điều kiện khác khi điều kiện trước đó sai.',
        else: 'Chạy khối mặc định này khi các điều kiện trước đều sai.',
        for: 'Lặp mã theo chuỗi, phạm vi hoặc điều kiện vòng lặp.',
        while: 'Lặp mã trong khi điều kiện vẫn đúng.',
        returnSuccess: 'Trả về 0 để cho biết chương trình đã kết thúc thành công.',
        returnVoid: 'Kết thúc hàm ngay lập tức và quay lại nơi gọi.',
        returnValue: 'Kết thúc hàm và trả kết quả về nơi gọi.',
        importModule: 'Nhập thư viện hoặc mô-đun mà chương trình cần.',
        input: 'Đọc dữ liệu bàn phím từ người dùng và lưu lại.',
        print: 'Hiển thị văn bản hoặc kết quả tính toán lên màn hình.',
        consoleLog: 'Hiển thị thông báo trong console của trình duyệt hoặc terminal.'
    }
};

const ALIASES = {
    'en-GB': 'en-US',
    'es-ES': 'es-MX',
    'pt-PT': 'pt-BR'
};

function normalizeLocale(value) {
    const parts = String(value || '').trim().replace(/_/g, '-').split('-').filter(Boolean);
    if (!parts.length) return 'en-US';

    return parts.map((part, index) => {
        if (index === 0) return part.toLowerCase();
        if (/^[A-Za-z]{2}$/.test(part) || /^\d{3}$/.test(part)) return part.toUpperCase();
        if (/^[A-Za-z]{4}$/.test(part)) return part[0].toUpperCase() + part.slice(1).toLowerCase();
        return part;
    }).join('-');
}

function resolveCatalogLocale(locale) {
    const normalized = normalizeLocale(locale);
    if (CATALOGS[normalized]) return normalized;
    if (ALIASES[normalized] && CATALOGS[ALIASES[normalized]]) return ALIASES[normalized];

    const language = normalized.split('-')[0];
    const sameLanguage = Object.keys(CATALOGS).find((key) => key.split('-')[0] === language);
    return sameLanguage || 'en-US';
}

function hasBuiltInCatalog(locale) {
    const normalized = normalizeLocale(locale);
    if (CATALOGS[normalized]) return true;
    if (ALIASES[normalized] && CATALOGS[ALIASES[normalized]]) return true;
    const language = normalized.split('-')[0];
    return Object.keys(CATALOGS).some((key) => key.split('-')[0] === language);
}

function getLanguageLabel(locale) {
    const normalized = normalizeLocale(locale);
    const option = LANGUAGE_OPTIONS.find((item) => item.locale === normalized);
    return option ? `${option.nativeName} (${normalized})` : normalized;
}

let reverseIndex = null;
function getReverseIndex() {
    if (reverseIndex) return reverseIndex;

    reverseIndex = new Map();
    for (const [source, key] of Object.entries(SOURCE_TO_KEY)) {
        reverseIndex.set(source, key);
    }

    for (const catalog of Object.values(CATALOGS)) {
        for (const [key, value] of Object.entries(catalog)) {
            reverseIndex.set(value, key);
        }
    }

    return reverseIndex;
}

function translateGeneratedComment(text, locale) {
    const raw = String(text || '').trim();
    if (!raw) return raw;

    const key = getReverseIndex().get(raw);
    if (!key) return raw;

    const catalogLocale = resolveCatalogLocale(locale);
    const catalog = CATALOGS[catalogLocale] || CATALOGS['en-US'];
    return catalog[key] || CATALOGS['en-US'][key] || raw;
}

module.exports = {
    LANGUAGE_OPTIONS,
    normalizeLocale,
    getLanguageLabel,
    hasBuiltInCatalog,
    translateGeneratedComment
};
